export const productTypes = {
  GET_PRODUCTS: 'GET_PRODUCTS',
  GET_PRODUCTS_ERROR: 'GET_PRODUCTS_ERROR',
  PRODUCT_INDEX: 'PRODUCT_INDEX',
  PRODUCT_INDEX_ERR: 'PRODUCT_INDEX_ERR',
  REMOVE_SELECTED_PRODUCT: 'REMOVE_SELECTED_PRODUCT',
};

export const basketTypes = {
  GET_BASKET_PRODUCTS: 'GET_BASKET_PRODUCTS',
  GET_BASKET_PRODUCTS_ERR: 'GET_BASKET_PRODUCTS_ERR',
  ADD_TO_BASKET: 'ADD_TO_BASKET',
  ADD_TO_BASKET_ERR: 'ADD_TO_BASKET_ERR',
  REMOVE_FROM_BASKET: 'REMOVE_FROM_BASKET',
};
